import Head from "next/head";
import React from "react";
import styles from "./main-layout.module.css";
import { signOut } from "next-auth/react";
import Link from "next/link";

interface LayoutProps {
  title: string;
  home?: boolean;
}

const Layout: React.FC<LayoutProps> = ({ title, children, home = false }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <footer className={styles.footer}>
        {!home && (
          <a
            style={{ cursor: "pointer" }}
            onClick={(e) => {
              e.preventDefault();
              signOut({
                redirect: false,
              });
            }}
          >
            Ausloggen
          </a>
        )}
        <Link href="/privacy">Datenschutz</Link>
      </footer>
    </div>
  );
};

export default Layout;
